[2022-06-15 13:57:13,622] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-06-15T08:27:10.657182+00:00 [queued]>
[2022-06-15 13:57:13,632] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-06-15T08:27:10.657182+00:00 [queued]>
[2022-06-15 13:57:13,632] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 13:57:13,633] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-15 13:57:13,633] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 13:57:13,647] {taskinstance.py:1378} INFO - Executing <Task(PostgresToElasticOperator): connections_to_es> on 2022-06-15 08:27:10.657182+00:00
[2022-06-15 13:57:13,672] {standard_task_runner.py:52} INFO - Started process 4790 to run task
[2022-06-15 13:57:13,678] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'elasticsearch_dag', 'connections_to_es', 'manual__2022-06-15T08:27:10.657182+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/elasticsearch_dag.py', '--cfg-path', '/tmp/tmpguov5cja', '--error-file', '/tmp/tmp5ncgr96f']
[2022-06-15 13:57:13,680] {standard_task_runner.py:80} INFO - Job 106: Subtask connections_to_es
[2022-06-15 13:57:13,810] {task_command.py:370} INFO - Running <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-06-15T08:27:10.657182+00:00 [running]> on host TIGER0990.tigeranalytics.local
[2022-06-15 13:57:13,923] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elasticsearch_dag
AIRFLOW_CTX_TASK_ID=connections_to_es
AIRFLOW_CTX_EXECUTION_DATE=2022-06-15T08:27:10.657182+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-15T08:27:10.657182+00:00
[2022-06-15 13:57:13,950] {base.py:68} INFO - Using connection ID 'elasticsearch_default' for task execution.
[2022-06-15 13:57:13,982] {base.py:68} INFO - Using connection ID '***_default' for task execution.
[2022-06-15 13:57:14,003] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/smita/airflow/plugins/elasticsearch_plugin/operators/postgres_to_elastic.py", line 27, in execute
    cur.execute(sql)
NameError: name 'sql' is not defined
[2022-06-15 13:57:14,029] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=elasticsearch_dag, task_id=connections_to_es, execution_date=20220615T082710, start_date=20220615T082713, end_date=20220615T082714
[2022-06-15 13:57:14,046] {standard_task_runner.py:92} ERROR - Failed to execute job 106 for task connections_to_es (name 'sql' is not defined; 4790)
[2022-06-15 13:57:14,053] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-15 13:57:14,138] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
