[2022-06-01 20:03:31,590] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available __airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__ [queued]>
[2022-06-01 20:03:31,594] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available __airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__ [queued]>
[2022-06-01 20:03:31,594] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 20:03:31,595] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-01 20:03:31,595] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 20:03:31,604] {taskinstance.py:1378} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-01-01 00:00:00+00:00
[2022-06-01 20:03:31,625] {standard_task_runner.py:52} INFO - Started process 11716 to run task
[2022-06-01 20:03:31,629] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '__airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp24w1vgpm', '--error-file', '/tmp/tmpg_8wuq_3']
[2022-06-01 20:03:31,630] {standard_task_runner.py:80} INFO - Job 16: Subtask is_api_available
[2022-06-01 20:03:31,662] {task_command.py:370} INFO - Running <TaskInstance: user_processing.is_api_available __airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__ [running]> on host TIGER0990.tigeranalytics.local
[2022-06-01 20:03:31,694] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__airflow_temporary_run_2022-06-01T10:53:33.458279+00:00__
[2022-06-01 20:03:31,695] {http.py:97} INFO - Poking: api/
[2022-06-01 20:03:31,700] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-06-01 20:03:31,701] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-06-01 20:03:32,330] {base.py:301} INFO - Success criteria met. Exiting.
[2022-06-01 20:03:32,338] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220101T000000, start_date=20220601T143331, end_date=20220601T143332
[2022-06-01 20:03:32,373] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-01 20:03:32,399] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
