[2022-06-15 14:04:56,509] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-06-15T08:34:53.814255+00:00 [queued]>
[2022-06-15 14:04:56,518] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-06-15T08:34:53.814255+00:00 [queued]>
[2022-06-15 14:04:56,518] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 14:04:56,519] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-15 14:04:56,519] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 14:04:56,529] {taskinstance.py:1378} INFO - Executing <Task(PostgresToElasticOperator): connections_to_es> on 2022-06-15 08:34:53.814255+00:00
[2022-06-15 14:04:56,552] {standard_task_runner.py:52} INFO - Started process 12602 to run task
[2022-06-15 14:04:56,557] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'elasticsearch_dag', 'connections_to_es', 'manual__2022-06-15T08:34:53.814255+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/elasticsearch_dag.py', '--cfg-path', '/tmp/tmpz3lrb0e6', '--error-file', '/tmp/tmp85w6o7z_']
[2022-06-15 14:04:56,559] {standard_task_runner.py:80} INFO - Job 116: Subtask connections_to_es
[2022-06-15 14:04:56,667] {task_command.py:370} INFO - Running <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-06-15T08:34:53.814255+00:00 [running]> on host TIGER0990.tigeranalytics.local
[2022-06-15 14:04:56,780] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elasticsearch_dag
AIRFLOW_CTX_TASK_ID=connections_to_es
AIRFLOW_CTX_EXECUTION_DATE=2022-06-15T08:34:53.814255+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-15T08:34:53.814255+00:00
[2022-06-15 14:04:56,807] {base.py:68} INFO - Using connection ID 'elasticsearch_default' for task execution.
[2022-06-15 14:04:56,831] {base.py:68} INFO - Using connection ID '***_default' for task execution.
[2022-06-15 14:04:56,853] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/smita/airflow/plugins/elasticsearch_plugin/operators/postgres_to_elastic.py", line 30, in execute
    es.add_doc(index=self.index, doc_type='external', body=doc)
TypeError: add_doc() got an unexpected keyword argument 'body'
[2022-06-15 14:04:56,886] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=elasticsearch_dag, task_id=connections_to_es, execution_date=20220615T083453, start_date=20220615T083456, end_date=20220615T083456
[2022-06-15 14:04:56,900] {standard_task_runner.py:92} ERROR - Failed to execute job 116 for task connections_to_es (add_doc() got an unexpected keyword argument 'body'; 12602)
[2022-06-15 14:04:56,936] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-15 14:04:57,002] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
