[2022-06-15 13:58:23,533] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-06-15T08:28:21.426125+00:00 [queued]>
[2022-06-15 13:58:23,542] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-06-15T08:28:21.426125+00:00 [queued]>
[2022-06-15 13:58:23,542] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 13:58:23,543] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-15 13:58:23,543] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 13:58:23,553] {taskinstance.py:1378} INFO - Executing <Task(PostgresToElasticOperator): connections_to_es> on 2022-06-15 08:28:21.426125+00:00
[2022-06-15 13:58:23,577] {standard_task_runner.py:52} INFO - Started process 5945 to run task
[2022-06-15 13:58:23,582] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'elasticsearch_dag', 'connections_to_es', 'manual__2022-06-15T08:28:21.426125+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/elasticsearch_dag.py', '--cfg-path', '/tmp/tmpbb537sg0', '--error-file', '/tmp/tmpdhbhlrap']
[2022-06-15 13:58:23,584] {standard_task_runner.py:80} INFO - Job 108: Subtask connections_to_es
[2022-06-15 13:58:23,703] {task_command.py:370} INFO - Running <TaskInstance: elasticsearch_dag.connections_to_es manual__2022-06-15T08:28:21.426125+00:00 [running]> on host TIGER0990.tigeranalytics.local
[2022-06-15 13:58:23,845] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elasticsearch_dag
AIRFLOW_CTX_TASK_ID=connections_to_es
AIRFLOW_CTX_EXECUTION_DATE=2022-06-15T08:28:21.426125+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-15T08:28:21.426125+00:00
[2022-06-15 13:58:23,878] {base.py:68} INFO - Using connection ID 'elasticsearch_default' for task execution.
[2022-06-15 13:58:23,907] {base.py:68} INFO - Using connection ID '***_default' for task execution.
[2022-06-15 13:58:23,933] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/smita/airflow/plugins/elasticsearch_plugin/operators/postgres_to_elastic.py", line 30, in execute
    es.add_doc(index=self.index, doc_type='external', doc=doc)
  File "/home/smita/airflow/plugins/elasticsearch_plugin/hooks/elastic_hook.py", line 32, in add_doc
    res = self.es.index(index=index, doc_type=doc_type, doc=doc)
  File "/home/smita/miniconda3/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: index() got an unexpected keyword argument 'doc'
[2022-06-15 13:58:23,965] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=elasticsearch_dag, task_id=connections_to_es, execution_date=20220615T082821, start_date=20220615T082823, end_date=20220615T082823
[2022-06-15 13:58:23,975] {standard_task_runner.py:92} ERROR - Failed to execute job 108 for task connections_to_es (index() got an unexpected keyword argument 'doc'; 5945)
[2022-06-15 13:58:24,001] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-15 13:58:24,067] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
